<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AiOrchestrator.SharedFunctionalTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\root\AiOrchestrator.Server\AiOrchestrator.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
